runtime: nodejs20
instance_class: F2
env_variables:
  NODE_ENV: 'production'
  PORT: '8080'
  DB_HOST: '/cloudsql/mindful-silo-433713-m9:asia-south1:postgres-db'
  INSTANCE_UNIX_SOCKET: '/cloudsql/mindful-silo-433713-m9:asia-south1:postgres-db'
  PROJECTID: 43626213410
  BUCKET: interview-quesiton
  KEYFILENAME: mindful-silo-433713-m9-b576d80448cf.json

  
entrypoint: npm run prod
